apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshua-c-webb/argocd-app-of-apps.git
    targetRevision: HEAD
    path: manifests/new-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
